#!/usr/bin/env python3

import sys

registers = [0 for i in range(16)]
i_register = 0
pc = 512
memory = bytearray(4096)
stack = []

def load_rom(rom_path):
    with open(rom_path, 'rb') as rom:
        i = pc
        for byte in rom.read():
            memory[i] = byte
            i += 1

def fetch_opcode():
    # program counter should always be on an even address
    assert(pc % 2 == 0)

    return memory[pc:pc+2].hex()

def exec_instr(opcode):
    global pc
    pc += 2

rom_path = sys.argv[1]
load_rom(rom_path)

while True:
    opcode = fetch_opcode()
    exec_instr(opcode)
